language: go
go:
  - "1.13"
  - "master"
matrix:
  allow_failures:
    - go: "master"
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -v -race -bench . -benchmem ./...
  - go test -v -tags binary_log -race -bench . -benchmem ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)